# Generated by Django 4.2.16 on 2025-05-26 06:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MaritalStatusCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plcyNo', models.CharField(max_length=255)),
                ('plcyNm', models.CharField(max_length=255)),
                ('plcyKywdNm', models.CharField(max_length=255)),
                ('plcyExplnCn', models.TextField()),
                ('plcySprtCn', models.TextField()),
                ('aplyYmD', models.CharField(max_length=255)),
                ('jobCd', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='policies.jobcode')),
                ('mrgSttsCd', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='policies.maritalstatuscode')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SchoolCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PolicyScrap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='policies.policy')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='policy',
            name='regions',
            field=models.ManyToManyField(blank=True, to='policies.region'),
        ),
        migrations.AddField(
            model_name='policy',
            name='schoolCd',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='policies.schoolcode'),
        ),
    ]
