# Generated by Django 4.2.16 on 2025-05-26 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DepositProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fin_prdt_cd', models.CharField(max_length=50)),
                ('fin_prdt_nm', models.CharField(max_length=255)),
                ('fin_co_no', models.CharField(max_length=255)),
                ('kor_co_nm', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cur_unit', models.CharField(max_length=255)),
                ('cur_nm', models.CharField(max_length=255)),
                ('ttb', models.CharField(max_length=255)),
                ('tts', models.CharField(max_length=255)),
                ('deal_bas_r', models.CharField(max_length=255)),
                ('bkpr', models.CharField(max_length=255)),
                ('yy_efee_r', models.CharField(max_length=255)),
                ('ten_dd_efee_r', models.CharField(max_length=255)),
                ('kftc_deal_bas_r', models.CharField(max_length=255)),
                ('kftc_bkpr', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SavingProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fin_prdt_cd', models.CharField(max_length=50)),
                ('fin_prdt_nm', models.CharField(max_length=255)),
                ('fin_co_no', models.CharField(max_length=255)),
                ('kor_co_nm', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SavingOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fin_prdt_cd', models.CharField(max_length=50)),
                ('fin_co_no', models.CharField(max_length=255)),
                ('rsrv_type', models.CharField(max_length=255)),
                ('rsrv_type_nm', models.CharField(max_length=255)),
                ('save_trm', models.IntegerField()),
                ('intr_rate2', models.FloatField()),
                ('saving_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finances.savingproduct')),
            ],
        ),
        migrations.CreateModel(
            name='DepositOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fin_prdt_cd', models.CharField(max_length=50)),
                ('fin_co_no', models.CharField(max_length=255)),
                ('save_trm', models.IntegerField()),
                ('intr_rate2', models.FloatField()),
                ('deposit_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finances.depositproduct')),
            ],
        ),
    ]
